openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Sample API'
  description: Buy or rent spacecrafts

paths:
  /spacecrafts/{spacecraftId}:
    parameters:
      - name: spacecraftId
        description: The unique identifier of the spacecraft
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/SpacecraftId'
      - name: spacecraftName
        description: The name of the spacecraft
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/SpacecraftId'
      - name: key
        description: The key of the spacecraft
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/SpacecraftId' 
      - name: abc
        description: The key of the spacecraft
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/SpacecraftId'
      - name: test qp
        description: The key of the spacecraft
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/SpacecraftId' 
      - name: test qp2
        description: The key of the spacecraft
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/SpacecraftId'                       
    get:
      summary: Read a spacecraft modified
      responses:
        '200':
          description: The spacecraft corresponding to the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
        404:
          description: No spacecraft found for the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        502:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'             
components:
  schemas:
    SpacecraftId:
      description: The unique identifier of a spacecraft
      type: string
    Spacecraft:
      type: object
      required:
        - id
        - name
        - type
      properties:
        id:
          $ref: '#/components/schemas/SpacecraftId'
        name:
          type: string
        type:
          type: string
          enum:
            - capsule
            - probe
            - satellite
            - spaceplane
            - station
        description:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: []